import Head from 'next/head';

import Link from "next/link";


export default function Home() {
    return (
        <>
            <Head>
                <title>Static page only edited</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-[#f4e357] w-full h-[100vh] pt-5">
                <div className="container px-5 mx-auto">
                    <div className="grid grid-cols-3 gap-4">
                        {[...Array(5)].map((_number, key)=>{
                            return(
                                <>
                                    <div key={key} className="rounded-md p-5 flex items-center justify-center bg-slate-500 text-white font-extrabold text-3xl">
                                        {key}
                                    </div>
                                </>
                            )
                        })}
                    </div>
                </div>

                <div className="w-full flex items-center mt-5 justify-center">
                    <Link href="/staticrevalidate">
                        <button className="mx-3 px-3 py-5 font-extrabold rounded-md bg-neutral-500">
                            Go to static with revalidate page
                        </button>
                    </Link>
                    <Link href="/server">
                        <button className="mx-3 px-3 py-5 font-extrabold rounded-md bg-neutral-500">
                            Go to server page
                        </button>
                    </Link>
                </div>
            </div>
        </>
    )
}
