import Head from 'next/head';

import Link from "next/link";

export default function Static({numbers}) {
    return(
        <>
            <Head>
                <title>Static with revalidation page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-[#d4ffe0] w-full h-[100vh] pt-5">
                <div className="container px-5 mx-auto">
                    <div className="grid grid-cols-3 gap-4">
                        {[...Array(numbers)].map((_number, key)=>{
                            return(
                                <>
                                    <div key={key} className="rounded-md p-5 flex items-center justify-center bg-slate-500 text-white font-extrabold text-3xl">
                                        {key}
                                    </div>
                                </>
                            )
                        })}
                    </div>
                </div>

                <div className="w-full flex items-center mt-5 justify-center">
                    <Link href="/">
                        <button className="mx-3 px-3 py-5 font-extrabold rounded-md bg-neutral-500">
                            Go to static page
                        </button>
                    </Link>
                    <Link href="/server">
                        <button className="mx-3 px-3 py-5 font-extrabold rounded-md bg-neutral-500">
                            Go to server page
                        </button>
                    </Link>
                </div>
            </div>
        </>
    )

}

export async function getStaticProps(_context){
    const numbers = Math.floor(Math.random() * 15);

    return {
        props: {
            numbers
        },
        revalidate: 5
    }
}